[[main]]
name = "Dakwah"
url = "dakwah/"
weight = 1

[[main]]
name = "Ibadah"
url = "ibadah/"
weight = 2

[[main]]
name = "Overview"
parent = "Ibadah"
url = "ibadah/"
weight = 1


[[main]]
name = "Joining Islam"
parent  = "Ibadah"
url = "ibadah/ibadah-3"
weight = 2

[[main]]
name = "Marriage"
parent  = "Ibadah"
url = "ibadah/ibadah-1"
weight = 3

[[main]]
name = "Birth"
parent  = "Ibadah"
url = "ibadah/ibadah-2"
weight = 4

[[main]]
name = "Passing Away"
parent  = "Ibadah"
url = "ibadah/ibadah-4"
weight = 5

[[main]]
name = "Zakat, Infaq and Sadaqah"
parent  = "Ibadah"
url = "ibadah/ibadah-5"
weight = 6

[[main]]
name = "⏰Fasting Schedule Ramadhan 1443"
parent  = "Ibadah"
url = "ramadhan-1443"
weight = 7

[[main]]
name = "Prayer Schedule 2022 (Den Haag)"
parent  = "Ibadah"
url = "forms/schedule-sholat-den-haag-2022.pdf"
weight = 8

[[main]]
name = "Events"
url = "event/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

  
[[main]]
name = "Contact"
url = "contact/"
weight = 5

# main menu
[[main]]
name = "About"
url = "about/"
weight = 6

# main menu
[[main]]
name = "Overview"
parent  = "About"
url = "about/"
weight = 1

# main menu
[[main]]
name = "Membership"
parent  = "About"
url = "about/about-1"
weight = 2