[[main]]
name = "Dakwah"
url = "dakwah/"
weight = 1

[[main]]
name = "Ibadah"
url = "ibadah/"
weight = 2

[[main]]
name = "Overview"
parent = "Ibadah"
url = "ibadah/"
weight = 1


[[main]]
name = "Mualaf"
parent  = "Ibadah"
url = "ibadah/ibadah-3"
weight = 2

[[main]]
name = "Pernikahan"
parent  = "Ibadah"
url = "ibadah/ibadah-1"
weight = 3

[[main]]
name = "Kelahiran"
parent  = "Ibadah"
url = "ibadah/ibadah-2"
weight = 4

[[main]]
name = "Kematian"
parent  = "Ibadah"
url = "ibadah/ibadah-4"
weight = 5

[[main]]
name = "Zakat, Infaq dan Sadaqah"
parent  = "Ibadah"
url = "ibadah/ibadah-5"
weight = 6



[[main]]
name = "Events"
url = "event/"
weight = 3

  
[[main]]
name = "Kontak"
url = "contact/"
weight = 4

# main menu
[[main]]
name = "Tentang Kami"
url = "about/"
weight = 5
