[[main]]
name = "Dakwah"
url = "dakwah/"
weight = 1

[[main]]
name = "Ibadah"
url = "ibadah/"
weight = 2

[[main]]
name = "Overview"
parent = "Ibadah"
url = "ibadah/"
weight = 1


[[main]]
name = "Joining Islam"
parent  = "Ibadah"
url = "ibadah/ibadah-3"
weight = 2

[[main]]
name = "Marriage"
parent  = "Ibadah"
url = "ibadah/ibadah-1"
weight = 3

[[main]]
name = "Birth"
parent  = "Ibadah"
url = "ibadah/ibadah-2"
weight = 4

[[main]]
name = "Passing Away"
parent  = "Ibadah"
url = "ibadah/ibadah-4"
weight = 5

[[main]]
name = "Zakat, Infaq and Sadaqah"
parent  = "Ibadah"
url = "ibadah/ibadah-5"
weight = 6



[[main]]
name = "Events"
url = "event/"
weight = 3

  
[[main]]
name = "Contact"
url = "contact/"
weight = 4

# main menu
[[main]]
name = "About"
url = "about/"
weight = 5
