[[main]]
name = "Dakwah"
url = "dakwah/"
weight = 1

[[main]]
name = "Ibadah"
url = "ibadah/"
weight = 2

[[main]]
name = "Overview"
parent = "Ibadah"
url = "ibadah/"
weight = 1


[[main]]
name = "Mualaf"
parent  = "Ibadah"
url = "ibadah/toetreden-islam"
weight = 2

[[main]]
name = "Pernikahan"
parent  = "Ibadah"
url = "ibadah/islamitisch-trouwen"
weight = 3

[[main]]
name = "Kelahiran"
parent  = "Ibadah"
url = "ibadah/geboorte"
weight = 4

[[main]]
name = "Kematian"
parent  = "Ibadah"
url = "ibadah/overlijden"
weight = 5

[[main]]
name = "Zakat, Infaq dan Sadaqah"
parent  = "Ibadah"
url = "ibadah/sadaqah"
weight = 6


[[main]]
name = "Jadwal Sholat 2024 (Den Haag)"
parent  = "Ibadah"
url = "forms/schedule-sholat-den-haag-2024.pdf"
weight = 8


[[main]]
name = "Events"
url = "event/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

  
[[main]]
name = "Kontak"
url = "contact/"
weight = 5

# main menu
[[main]]
name = "Tentang Kami"
url = "about/"
weight = 6

# main menu
[[main]]
name = "Sejarah dan Perkembangan"
parent  = "Tentang Kami"
url = "about/"
weight = 1

# main menu
[[main]]
name = "Keanggotaan"
parent  = "Tentang Kami"
url = "about/about-1"
weight = 2