[[main]]
name = "Dakwah"
url = "dakwah/"
weight = 1

[[main]]
name = "Ibadah"
url = "ibadah/"
weight = 2

[[main]]
name = "Overview"
parent = "Ibadah"
url = "ibadah/"
weight = 1


[[main]]
name = "Joining Islam"
parent  = "Ibadah"
url = "ibadah/toetreden-islam"
weight = 2

[[main]]
name = "Marriage"
parent  = "Ibadah"
url = "ibadah/islamitisch-trouwen"
weight = 3

[[main]]
name = "Birth"
parent  = "Ibadah"
url = "ibadah/geboorte"
weight = 4

[[main]]
name = "Passing Away"
parent  = "Ibadah"
url = "ibadah/overlijden"
weight = 5

[[main]]
name = "Zakat, Infaq and Sadaqah"
parent  = "Ibadah"
url = "ibadah/sadaqah"
weight = 6


[[main]]
name = "Prayer Schedule 2022 (Den Haag)"
parent  = "Ibadah"
url = "forms/schedule-sholat-den-haag-2022.pdf"
weight = 8

[[main]]
name = "Events"
url = "event/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

  
[[main]]
name = "Contact"
url = "contact/"
weight = 5

# main menu
[[main]]
name = "About"
url = "about/"
weight = 6

# main menu
[[main]]
name = "Overview"
parent  = "About"
url = "about/"
weight = 1

# main menu
[[main]]
name = "Membership"
parent  = "About"
url = "about/about-1"
weight = 2