[build]
  publish = "public"
  command = "hugo --minify --gc -b https://www.ppmedenhaag.nl"
  
[build.environment]
  HUGO_VERSION = "0.87.0"
  TZ = "CET"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, s-max-age=86400"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/plugins/*" # js files should be set this way
  [headers.values]
    Cache-Control = "public, s-max-age=86400"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, s-max-age=86400"


[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

